# Generated by Django 4.2.10 on 2024-05-06 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_app', '0003_taskcomment_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment1',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/', verbose_name='First attachment'),
        ),
        migrations.AddField(
            model_name='task',
            name='attachment2',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/', verbose_name='Second attachment'),
        ),
        migrations.AddField(
            model_name='task',
            name='attachment3',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/', verbose_name='Third attachment'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/', verbose_name='First attachment for comment'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='attachment2',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/', verbose_name='Second attachment for comment'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='attachment3',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/', verbose_name='Third attachment for comment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completion date of task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date of task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Description of task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due date of task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done')], default='todo', max_length=11, verbose_name='Current status of task'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='comment',
            field=models.TextField(verbose_name='Content of the comment'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date of comment'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
