# Generated by Django 4.2.10 on 2024-05-06 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_app', '0004_task_attachment1_task_attachment2_task_attachment3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Assign this task to one or more team members.', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment1',
            field=models.FileField(blank=True, help_text='Upload a relevant file as the first attachment for this task.', null=True, upload_to='task_attachments/', verbose_name='First attachment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment2',
            field=models.FileField(blank=True, help_text='Upload a relevant file as the second attachment for this task.', null=True, upload_to='task_attachments/', verbose_name='Second attachment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment3',
            field=models.FileField(blank=True, help_text='Upload a relevant file as the third attachment for this task.', null=True, upload_to='task_attachments/', verbose_name='Third attachment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='The date and time the task was completed. Update this when the task is marked as done.', null=True, verbose_name='Completion date of task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the task was created. This is automatically set and should not be changed.', verbose_name='Creation date of task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Provide a detailed description of the task.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Optionally set a deadline for when the task needs to be completed.', null=True, verbose_name='Due date of task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done')], default='todo', help_text='Select the current status of the task. Choose from To Do, In Progress, In Review, or Done.', max_length=11, verbose_name='Current status of task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Enter a short, descriptive title for the task.', max_length=64, verbose_name='Title of task'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload a file related to this comment, if necessary.', null=True, upload_to='comment_attachments/', verbose_name='First attachment for comment'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='attachment2',
            field=models.FileField(blank=True, help_text='Optionally add a second file attachment related to this comment.', null=True, upload_to='comment_attachments/', verbose_name='Second attachment for comment'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='attachment3',
            field=models.FileField(blank=True, help_text='Optionally add a third file attachment related to this comment.', null=True, upload_to='comment_attachments/', verbose_name='Third attachment for comment'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='comment',
            field=models.TextField(help_text='The text content of the comment.'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time this comment was created. Automatically set at the time of creation.', verbose_name='Creation date of comment'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='creator',
            field=models.ForeignKey(help_text='The user who created this comment.', on_delete=django.db.models.deletion.CASCADE, related_name='created_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(help_text='The task this comment is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task_app.task'),
        ),
    ]
